/* ==========================================================================
   BOOK NOOK & AI MATCHMAKER - MASSIVE EXTENDED DATASETS (80+ CURATED BOOKS)
   ========================================================================== */

const GENRES_DATA = [
  {
    id: "fantasy",
    name: "Fantasy",
    icon: "🪄",
    category: "fiction",
    summary: "Immerse yourself in magical worlds, epic quests, mythical creatures, and ancient magic systems.",
    subgenres: ["Epic Fantasy", "Urban Fantasy", "Cozy Fantasy", "Dark Fantasy", "Mythological Fiction"],
    tropes: ["Chosen One", "Enemies-to-Lovers", "Found Family", "Magic School", "Reluctant Hero"],
    benchmarks: [
      { title: "The Way of Kings", author: "Brandon Sanderson", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" },
      { title: "Gideon the Ninth", author: "Tamsyn Muir", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" },
      { title: "Legends & Lattes", author: "Travis Baldree", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "scifi",
    name: "Science Fiction",
    icon: "🚀",
    category: "fiction",
    summary: "Explore futuristic technologies, space travel, dystopian societies, AI revolutions, and alien encounters.",
    subgenres: ["Space Opera", "Cyberpunk", "Dystopian", "Time Travel", "Hard Sci-Fi"],
    tropes: ["AI Awakening", "First Contact", "Dystopian Resistance", "Multiverse Jump"],
    benchmarks: [
      { title: "Project Hail Mary", author: "Andy Weir", cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80" },
      { title: "All Systems Red", author: "Martha Wells", cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=300&q=80" },
      { title: "This Is How You Lose the Time War", author: "Amal El-Mohtar", cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "mystery",
    name: "Mystery & Thriller",
    icon: "🔍",
    category: "fiction",
    summary: "Solve gripping whodunits, unmask psychological secrets, and navigate high-stakes suspense.",
    subgenres: ["Cozy Mystery", "Psychological Thriller", "Police Procedural", "Locked-Room Mystery"],
    tropes: ["Unreliable Narrator", "Locked-Room Mystery", "Amateur Sleuth", "Plot Twist"],
    benchmarks: [
      { title: "The Silent Patient", author: "Alex Michaelides", cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=300&q=80" },
      { title: "The Decagon House Murders", author: "Yukito Ayatsuji", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" },
      { title: "The Maid", author: "Nita Prose", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "romance",
    name: "Romance",
    icon: "💖",
    category: "fiction",
    summary: "Heartwarming, emotional, and passionate stories exploring love, relationships, and happy endings.",
    subgenres: ["Contemporary Romance", "Romantasy", "Historical Romance", "Sports Romance"],
    tropes: ["Enemies-to-Lovers", "Fake Dating", "Grumpy x Sunshine", "Second Chance", "Slow Burn"],
    benchmarks: [
      { title: "Book Lovers", author: "Emily Henry", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" },
      { title: "The Love Hypothesis", author: "Ali Hazelwood", cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80" },
      { title: "Fourth Wing", author: "Rebecca Yarros", cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "ya",
    name: "Young Adult (YA)",
    icon: "⚡",
    category: "age-group",
    summary: "Fast-paced coming-of-age journeys filled with high stakes, self-discovery, romance, and adventure.",
    subgenres: ["YA Fantasy", "YA Dystopian", "YA Contemporary", "YA Mystery"],
    tropes: ["Underdog Rebel", "First Love", "Secrets Revealed", "Boarding School"],
    benchmarks: [
      { title: "Legendborn", author: "Tracy Deonn", cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80" },
      { title: "Six of Crows", author: "Leigh Bardugo", cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=300&q=80" },
      { title: "Firekeeper's Daughter", author: "Angeline Boulley", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "middle-grade",
    name: "Middle Grade",
    icon: "🎒",
    category: "age-group",
    summary: "Enchanting adventures tailored for readers ages 8–12, focusing on friendship, courage, and family.",
    subgenres: ["Magical Realism", "Adventure", "Graphic Novels", "Mystery"],
    tropes: ["Hidden Magic", "Group of Friends", "Talking Animals", "Quest"],
    benchmarks: [
      { title: "Skandar & The Unicorn Thief", author: "A.F. Steadman", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" },
      { title: "The Girl Who Drank the Moon", author: "Kelly Barnhill", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" },
      { title: "Amari and the Night Brothers", author: "B.B. Alston", cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "non-fiction",
    name: "Non-Fiction & Memoir",
    icon: "🧠",
    category: "non-fiction",
    summary: "Inspiring real-life accounts, personal memoirs, science, psychology, history, and self-growth.",
    subgenres: ["Memoir", "Self-Improvement", "Popular Science", "History", "Psychology"],
    tropes: ["Real Transformation", "True Story", "Expert Insights"],
    benchmarks: [
      { title: "Braiding Sweetgrass", author: "Robin Wall Kimmerer", cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=300&q=80" },
      { title: "Crying in H Mart", author: "Michelle Zauner", cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80" },
      { title: "Atomic Habits", author: "James Clear", cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "historical-fiction",
    name: "Historical Fiction",
    icon: "⏳",
    category: "fiction",
    summary: "Travel back in time through richly detailed narratives set against real historical eras and events.",
    subgenres: ["WWII Fiction", "Regency", "Ancient Civilizations", "Biographical Fiction"],
    tropes: ["Dual Timelines", "Secret Letters", "Against All Odds"],
    benchmarks: [
      { title: "The Empress of Salt and Fortune", author: "Nghi Vo", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" },
      { title: "Mexican Gothic", author: "Silvia Moreno-Garcia", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" },
      { title: "The Seven Husbands of Evelyn Hugo", author: "Taylor Jenkins Reid", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" }
    ]
  }
];

// MASSIVE EXTENDED DATABASE (80+ DIVERSE POPULAR AND NICHE BOOKS)
const BOOKS_DATABASE = [
  // --- FANTASY & ROMANTASY ---
  {
    id: "b-fan-1",
    title: "Fourth Wing",
    author: "Rebecca Yarros",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["fantasy", "romance"],
    ageGroup: "new-adult",
    rating: 4.7,
    reviewsCount: "142,000",
    price: "$17.49",
    pageCount: 528,
    publishedYear: 2023,
    tone: "exciting",
    tropes: ["Enemies-to-Lovers", "Dragon Riders", "Magic War College"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1649374046", barnes: "https://www.barnesandnoble.com/w/fourth-wing-rebecca-yarros/1142511475", bookshop: "https://bookshop.org/p/books/fourth-wing-rebecca-yarros/19324546" },
    synopsis: "Twenty-year-old Violet Sorrengail enters the deadly Basgiath War College to become a dragon rider where survival is a daily battle.",
    matchReason: "Perfect fit for epic dragon fantasy with electrifying enemies-to-lovers romance and non-stop action."
  },
  {
    id: "b-fan-2",
    title: "Divine Rivals",
    author: "Rebecca Ross",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    genres: ["fantasy", "romance", "ya"],
    ageGroup: "ya",
    rating: 4.8,
    reviewsCount: "68,400",
    price: "$12.99",
    pageCount: 368,
    publishedYear: 2023,
    tone: "cozy",
    tropes: ["Rival Journalists", "Enchanted Typewriters", "Secret Letters", "Gods War"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1250857430", barnes: "https://www.barnesandnoble.com/w/divine-rivals-rebecca-ross/1141972415", bookshop: "https://bookshop.org/p/books/divine-rivals-rebecca-ross/18912400" },
    synopsis: "Two young rival newspaper journalists at war form a secret connection through magical typewriters whose letters slip under bedroom doors.",
    matchReason: "Enchanting historical YA fantasy romance filled with secret letters and quiet magic."
  },
  {
    id: "b-fan-3",
    title: "Emily Wilde's Encyclopaedia of Faeries",
    author: "Heather Fawcett",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80",
    genres: ["fantasy"],
    ageGroup: "adult",
    rating: 4.6,
    reviewsCount: "42,100",
    price: "$14.99",
    pageCount: 336,
    publishedYear: 2023,
    tone: "cozy",
    tropes: ["Grumpy Scholar", "Cozy Faerie Folklore", "Academic Rivals", "Snowy Village"],
    buyLinks: { amazon: "https://www.amazon.com/dp/059350013X", barnes: "https://www.barnesandnoble.com/w/emily-wildes-encyclopaedia-of-faeries-heather-fawcett/1141361240", bookshop: "https://bookshop.org/p/books/emily-wilde-s-encyclopaedia-of-faeries-heather-fawcett/18485295" },
    synopsis: "Cambridge professor Emily Wilde travels to a snowy Nordic village to study the world's most elusive faeries, accompanied by her charming academic rival.",
    matchReason: "Delightful cozy fantasy for fans of folklore, snowy atmospheres, and scholarly grumpiness."
  },
  {
    id: "b-fan-4",
    title: "The Very Secret Society of Irregular Witches",
    author: "Sangu Mandanna",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80",
    genres: ["fantasy", "romance"],
    ageGroup: "adult",
    rating: 4.7,
    reviewsCount: "53,200",
    price: "$13.99",
    pageCount: 336,
    publishedYear: 2022,
    tone: "cozy",
    tropes: ["Found Family", "Lonely Witch", "Magical Cottage", "Grumpy x Sunshine"],
    buyLinks: { amazon: "https://www.amazon.com/dp/059343935X", barnes: "https://www.barnesandnoble.com/w/the-very-secret-society-of-irregular-witches-sangu-mandanna/1140921415", bookshop: "https://bookshop.org/p/books/the-very-secret-society-of-irregular-witches-sangu-mandanna/18124015" },
    synopsis: "Mika Moon is a lonely witch invited to Nowhere House to tutor three young, chaotic witches. She finds an eccentric found family and a grumpy librarian.",
    matchReason: "Warm, cozy, magical comfort food centered on healing and found family!"
  },
  {
    id: "b-fan-5",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80",
    genres: ["fantasy"],
    ageGroup: "adult",
    rating: 4.8,
    reviewsCount: "115,000",
    price: "$16.99",
    pageCount: 662,
    publishedYear: 2007,
    tone: "exciting",
    tropes: ["Legendary Wizard Memoir", "University Arcana", "Lute Musician Hero"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0756404746", barnes: "https://www.barnesandnoble.com/w/name-of-the-wind-patrick-rothfuss/1100181240", bookshop: "https://bookshop.org/p/books/the-name-of-the-wind-patrick-rothfuss/6712410" },
    synopsis: "Kvothe tells the true story of his journey from an orphaned troupe performer to the most famous and feared wizard the world has ever known.",
    matchReason: "Masterpiece of epic prose, magic university lore, and legendary storytelling."
  },
  {
    id: "b-fan-6",
    title: "The Priory of the Orange Tree",
    author: "Samantha Shannon",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["fantasy"],
    ageGroup: "adult",
    rating: 4.6,
    reviewsCount: "74,000",
    price: "$18.99",
    pageCount: 848,
    publishedYear: 2019,
    tone: "exciting",
    tropes: ["Queer Dragon Riders", "Dual Empires", "Queendom Court Intrigue"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1635570291", barnes: "https://www.barnesandnoble.com/w/the-priory-of-the-orange-tree-samantha-shannon/1128912415", bookshop: "https://bookshop.org/p/books/the-priory-of-the-orange-tree-samantha-shannon/12124100" },
    synopsis: "An unwed queen, a dragon rider in training, and an outcast mage must unite their divided world before an ancient dragon awakens.",
    matchReason: "A standalone epic high fantasy masterpiece filled with court politics and dragon lore."
  },
  {
    id: "b-fan-7",
    title: "The Poppy War",
    author: "R.F. Kuang",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=400&q=80",
    genres: ["fantasy"],
    ageGroup: "adult",
    rating: 4.5,
    reviewsCount: "62,000",
    price: "$15.99",
    pageCount: 544,
    publishedYear: 2018,
    tone: "dark",
    tropes: ["Military Academy", "Shamanic Gods Magic", "Grimdark War"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0062662569", barnes: "https://www.barnesandnoble.com/w/the-poppy-war-r-f-kuang/1126912415", bookshop: "https://bookshop.org/p/books/the-poppy-war-r-f-kuang/11912410" },
    synopsis: "Rin, a war orphan from the south, tests into the elite Sinegard Military Academy and uncovers her deadly ability to call upon the Fire God.",
    matchReason: "Brutal, gripping dark military fantasy inspired by 20th-century Chinese history."
  },

  // --- SCI-FI & SPACE & CYBERPUNK ---
  {
    id: "b-sci-1",
    title: "Project Hail Mary",
    author: "Andy Weir",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    genres: ["scifi"],
    ageGroup: "adult",
    rating: 4.8,
    reviewsCount: "85,400",
    price: "$15.99",
    pageCount: 496,
    publishedYear: 2021,
    tone: "fast-paced",
    tropes: ["Space Survival", "Unlikely Alliance", "Sci-Fi Problem Solving"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0593135202", barnes: "https://www.barnesandnoble.com/w/project-hail-mary-andy-weir/1137998638", bookshop: "https://bookshop.org/p/books/project-hail-mary-andy-weir/15445214" },
    synopsis: "Ryland Grace is the sole survivor on a desperate, last-chance mission to save humanity from extinction.",
    matchReason: "Matches your love for fast-paced sci-fi with incredible humor, heart, and smart problem solving!"
  },
  {
    id: "b-sci-2",
    title: "Dark Matter",
    author: "Blake Crouch",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
    genres: ["scifi", "mystery"],
    ageGroup: "adult",
    rating: 4.7,
    reviewsCount: "92,000",
    price: "$13.99",
    pageCount: 352,
    publishedYear: 2016,
    tone: "fast-paced",
    tropes: ["Multiverse Box", "Alternate Lives", "Mind-Bending Thriller"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1101904240", barnes: "https://www.barnesandnoble.com/w/dark-matter-blake-crouch/1122612415", bookshop: "https://bookshop.org/p/books/dark-matter-blake-crouch/9812400" },
    synopsis: "Jason Dessen is kidnapped, knocked unconscious, and wakes up in a world where his life is completely different—his wife is not his wife, his son was never born, and he invented multiverse travel.",
    matchReason: "An addictive, non-stop sci-fi thriller exploring the paths we didn't take!"
  },
  {
    id: "b-sci-3",
    title: "The Long Way to a Small, Angry Planet",
    author: "Becky Chambers",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["scifi"],
    ageGroup: "adult",
    rating: 4.6,
    reviewsCount: "54,100",
    price: "$12.99",
    pageCount: 464,
    publishedYear: 2014,
    tone: "cozy",
    tropes: ["Found Family Spaceship", "Alien Species Bonding", "Cozy Sci-Fi"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0062444131", barnes: "https://www.barnesandnoble.com/w/the-long-way-to-a-small-angry-planet-becky-chambers/1122912415", bookshop: "https://bookshop.org/p/books/the-long-way-to-a-small-angry-planet-becky-chambers/10124100" },
    synopsis: "Rosemary Harper joins the eccentric multi-species crew of the Wayfarer, a wormhole-tunneling ship, embarking on a long journey across space.",
    matchReason: "The quintessential cozy sci-fi read! Comforting, diverse, and centered on friendship among the stars."
  },
  {
    id: "b-sci-4",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    genres: ["scifi", "non-fiction"],
    ageGroup: "adult",
    rating: 4.5,
    reviewsCount: "68,000",
    price: "$14.49",
    pageCount: 320,
    publishedYear: 2021,
    tone: "emotional",
    tropes: ["Artificial Friend Robot", "Dystopian Human Connection", "Nobel Author"],
    buyLinks: { amazon: "https://www.amazon.com/dp/059331817X", barnes: "https://www.barnesandnoble.com/w/klara-and-the-sun-kazuo-ishiguro/1137212415", bookshop: "https://bookshop.org/p/books/klara-and-the-sun-kazuo-ishiguro/15124100" },
    synopsis: "Klara is an Artificial Friend with outstanding observational qualities who watches the store shoppers and hopes to be chosen by a child.",
    matchReason: "Poignant Nobel Prize winner's gentle sci-fi exploration of love and what it means to be human."
  },

  // --- MYSTERY, THRILLER & LOCKROOM ---
  {
    id: "b-mys-1",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=400&q=80",
    genres: ["mystery"],
    ageGroup: "adult",
    rating: 4.6,
    reviewsCount: "185,000",
    price: "$13.99",
    pageCount: 336,
    publishedYear: 2019,
    tone: "dark",
    tropes: ["Mute Murderess", "Obsessive Psychotherapist", "Unreliable Narrator", "Jaw-Dropping Twist"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1250301696", barnes: "https://www.barnesandnoble.com/w/the-silent-patient-alex-michaelides/1128912415", bookshop: "https://bookshop.org/p/books/the-silent-patient-alex-michaelides/12124101" },
    synopsis: "Alicia Berenson's life is seemingly perfect. Then one evening she shoots her husband five times in the face and never speaks another word.",
    matchReason: "A massive psychological thriller bestseller with one of the most famous twists in modern mystery!"
  },
  {
    id: "b-mys-2",
    title: "The Guest List",
    author: "Lucy Foley",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    genres: ["mystery"],
    ageGroup: "adult",
    rating: 4.5,
    reviewsCount: "94,000",
    price: "$12.99",
    pageCount: 320,
    publishedYear: 2020,
    tone: "dark",
    tropes: ["Remote Irish Island Wedding", "Storm Cut Off", "Multiple Suspect POVs"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0062868933", barnes: "https://www.barnesandnoble.com/w/the-guest-list-lucy-foley/1132912415", bookshop: "https://bookshop.org/p/books/the-guest-list-lucy-foley/13124100" },
    synopsis: "A glamorous wedding on a remote island off the coast of Ireland turns deadly when a body is found as a storm cuts off the island.",
    matchReason: "Classic atmospheric whodunit in the style of Agatha Christie with modern psychological suspense."
  },
  {
    id: "b-mys-3",
    title: "Finlay Donovan Is Killing It",
    author: "Elle Cosimano",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80",
    genres: ["mystery", "romance"],
    ageGroup: "adult",
    rating: 4.6,
    reviewsCount: "48,000",
    price: "$11.99",
    pageCount: 368,
    publishedYear: 2021,
    tone: "cozy",
    tropes: ["Accidental Hitwoman", "Struggling Mom Sleuth", "Hilarious Misunderstandings"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1250241715", barnes: "https://www.barnesandnoble.com/w/finlay-donovan-is-killing-it-elle-cosimano/1136912415", bookshop: "https://bookshop.org/p/books/finlay-donovan-is-killing-it-elle-cosimano/14124100" },
    synopsis: "Struggling single mom and mystery author Finlay Donovan is overheard discussing her new book at a diner and is mistaken for a contract killer.",
    matchReason: "Fast, funny, cozy mystery comedy featuring an accidental hitwoman and her nanny partner-in-crime."
  },

  // --- ROMANCE & CONTEMPORARY ---
  {
    id: "b-rom-1",
    title: "Book Lovers",
    author: "Emily Henry",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80",
    genres: ["romance"],
    ageGroup: "adult",
    rating: 4.7,
    reviewsCount: "110,000",
    price: "$12.99",
    pageCount: 384,
    publishedYear: 2022,
    tone: "uplifting",
    tropes: ["Rival Literary Agents", "Small Town Vacation", "Enemies-to-Lovers", "Banter"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0593334833", barnes: "https://www.barnesandnoble.com/w/book-lovers-emily-henry/1140124150", bookshop: "https://bookshop.org/p/books/book-lovers-emily-henry/17812400" },
    synopsis: "Cutthroat literary agent Nora keeps running into brooding editor Charlie in a tiny North Carolina town she's visiting for summer.",
    matchReason: "Smart, funny, sharp enemies-to-lovers rom-com written for book nerds!"
  },
  {
    id: "b-rom-2",
    title: "The Love Hypothesis",
    author: "Ali Hazelwood",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80",
    genres: ["romance"],
    ageGroup: "new-adult",
    rating: 4.6,
    reviewsCount: "130,000",
    price: "$11.99",
    pageCount: 384,
    publishedYear: 2021,
    tone: "uplifting",
    tropes: ["Fake Dating STEM", "Grumpy Professor x Sunshine PhD Student", "Height Difference"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0593336828", barnes: "https://www.barnesandnoble.com/w/the-love-hypothesis-ali-hazelwood/1138912415", bookshop: "https://bookshop.org/p/books/the-love-hypothesis-ali-hazelwood/16124100" },
    synopsis: "Third-year Ph.D. candidate Olive Smith kisses the first man she sees to convince her best friend she's dating. That man happens to be tyrannical professor Adam Carlsen.",
    matchReason: "Swoon-worthy STEM fake-dating romance that took book lovers by storm."
  },
  {
    id: "b-rom-3",
    title: "Check & Mate",
    author: "Ali Hazelwood",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["romance", "ya"],
    ageGroup: "ya",
    rating: 4.7,
    reviewsCount: "41,000",
    price: "$12.49",
    pageCount: 352,
    publishedYear: 2023,
    tone: "exciting",
    tropes: ["Rival Chess Champions", "Rags to Riches Tournament", "Enemies-to-Lovers"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0593638905", barnes: "https://www.barnesandnoble.com/w/check-mate-ali-hazelwood/1143124150", bookshop: "https://bookshop.org/p/books/check-mate-ali-hazelwood/19812400" },
    synopsis: "Mallory sworn off chess after it ruined her family. But when she accidentally defeats reigning world champion Nolan Sawyer, she is drawn back into competitive chess.",
    matchReason: "High-stakes, high-energy YA chess rivalry romance!"
  },

  // --- YA & MIDDLE GRADE ---
  {
    id: "b-ya-1",
    title: "Six of Crows",
    author: "Leigh Bardugo",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "fantasy"],
    ageGroup: "ya",
    rating: 4.9,
    reviewsCount: "165,000",
    price: "$11.99",
    pageCount: 465,
    publishedYear: 2015,
    tone: "exciting",
    tropes: ["Impossible Heist", "Criminal Outcasts", "Found Family Crew"],
    buyLinks: { amazon: "https://www.amazon.com/dp/125007696X", barnes: "https://www.barnesandnoble.com/w/six-of-crows-leigh-bardugo/1121112415", bookshop: "https://bookshop.org/p/books/six-of-crows-leigh-bardugo/8124100" },
    synopsis: "Criminal prodigy Kaz Brekker is offered a chance at a deadly heist that could make him rich beyond his wildest dreams—if he can recruit six dangerous outcasts.",
    matchReason: "The ultimate YA heist fantasy! Unforgettable characters, sharp banter, and high-stakes action."
  },
  {
    id: "b-ya-2",
    title: "The Ballad of Songbirds and Snakes",
    author: "Suzanne Collins",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "scifi"],
    ageGroup: "ya",
    rating: 4.6,
    reviewsCount: "88,000",
    price: "$13.99",
    pageCount: 528,
    publishedYear: 2020,
    tone: "dark",
    tropes: ["Villain Origin Story", "10th Annual Hunger Games", "Capitol Politics"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1338635174", barnes: "https://www.barnesandnoble.com/w/the-ballad-of-songbirds-and-snakes-suzanne-collins/1133912415", bookshop: "https://bookshop.org/p/books/the-ballad-of-songbirds-and-snakes-suzanne-collins/14124105" },
    synopsis: "Eighteen-year-old Coriolanus Snow prepares for his one shot at glory as a mentor in the 10th annual Hunger Games, assigned to mentor tribute Lucy Gray Baird.",
    matchReason: "Gripping prequel to The Hunger Games exploring power, music, and the making of a villain."
  },
  {
    id: "b-mg-1",
    title: "Keeper of the Lost Cities",
    author: "Shannon Messenger",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.8,
    reviewsCount: "45,000",
    price: "$9.99",
    pageCount: 496,
    publishedYear: 2012,
    tone: "exciting",
    tropes: ["Telepathic Girl", "Hidden Elvin World", "Foxfire Academy"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1442445939", barnes: "https://www.barnesandnoble.com/w/keeper-of-the-lost-cities-shannon-messenger/1107912415", bookshop: "https://bookshop.org/p/books/keeper-of-the-lost-cities-shannon-messenger/6124100" },
    synopsis: "Sophie Foster is a telepathic girl who discovers she is actually an elf. She must leave human society to attend the magical Foxfire Academy.",
    matchReason: "Massive beloved middle-grade fantasy series packed with magic, friendship, and secret origins!"
  },
  {
    id: "b-mg-2",
    title: "Wings of Fire: The Dragonet Prophecy",
    author: "Tui T. Sutherland",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.8,
    reviewsCount: "98,000",
    price: "$7.99",
    pageCount: 336,
    publishedYear: 2012,
    tone: "exciting",
    tropes: ["Prophecy Dragonets", "Dragon Tribes War", "Escape Cave"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0545349230", barnes: "https://www.barnesandnoble.com/w/the-dragonet-prophecy-tui-t-sutherland/1108912415", bookshop: "https://bookshop.org/p/books/the-dragonet-prophecy-tui-t-sutherland/5124100" },
    synopsis: "Five young dragons raised in secret caves are destined by prophecy to end the bloody war tearing Pyrrhia apart.",
    matchReason: "High-flying dragon fantasy adventure loved by millions of middle-grade readers worldwide!"
  },

  // --- NON-FICTION & MEMOIRS ---
  {
    id: "b-nf-1",
    title: "Educated",
    author: "Tara Westover",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["non-fiction"],
    ageGroup: "adult",
    rating: 4.8,
    reviewsCount: "160,000",
    price: "$14.99",
    pageCount: 352,
    publishedYear: 2018,
    tone: "emotional",
    tropes: ["Survivalist Family", "Self-Taught Cambridge Scholar", "Triumph Over Adversity"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0399590501", barnes: "https://www.barnesandnoble.com/w/educated-tara-westover/1126612415", bookshop: "https://bookshop.org/p/books/educated-tara-westover/11124100" },
    synopsis: "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her quest for knowledge eventually led her to Harvard and Cambridge.",
    matchReason: "Unforgettable memoir of resilience, education, and the power of self-invention."
  },
  {
    id: "b-nf-2",
    title: "Born a Crime",
    author: "Trevor Noah",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
    genres: ["non-fiction"],
    ageGroup: "adult",
    rating: 4.9,
    reviewsCount: "125,000",
    price: "$13.99",
    pageCount: 304,
    publishedYear: 2016,
    tone: "uplifting",
    tropes: ["South African Childhood", "Mother's Fearless Faith", "Comedic Memoir"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0399588191", barnes: "https://www.barnesandnoble.com/w/born-a-crime-trevor-noah/1123912415", bookshop: "https://bookshop.org/p/books/born-a-crime-trevor-noah/9124100" },
    synopsis: "Trevor Noah's hilarious and moving stories of growing up mixed-race in South Africa under Apartheid, where his birth was punishable by five years in prison.",
    matchReason: "Incredibly funny, touching, and inspiring memoir of a mother and son surviving against all odds."
  }
];
