/* ==========================================================================
   BOOK NOOK & AI MATCHMAKER - MASSIVE 130+ BOOK DATABASE
   ========================================================================== */

const GENRES_DATA = [
  {
    id: "fantasy",
    name: "Fantasy",
    icon: "🪄",
    category: "fiction",
    summary: "Immerse yourself in magical worlds, epic quests, mythical creatures, and ancient magic systems.",
    subgenres: ["Epic Fantasy", "Urban Fantasy", "Cozy Fantasy", "Dark Fantasy", "Mythological Fiction"],
    tropes: ["Chosen One", "Enemies-to-Lovers", "Found Family", "Magic School", "Reluctant Hero"],
    benchmarks: [
      { title: "The Way of Kings", author: "Brandon Sanderson", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" },
      { title: "Gideon the Ninth", author: "Tamsyn Muir", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" },
      { title: "Legends & Lattes", author: "Travis Baldree", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "scifi",
    name: "Science Fiction",
    icon: "🚀",
    category: "fiction",
    summary: "Explore futuristic technologies, space travel, dystopian societies, AI revolutions, and alien encounters.",
    subgenres: ["Space Opera", "Cyberpunk", "Dystopian", "Time Travel", "Hard Sci-Fi"],
    tropes: ["AI Awakening", "First Contact", "Dystopian Resistance", "Multiverse Jump"],
    benchmarks: [
      { title: "Project Hail Mary", author: "Andy Weir", cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80" },
      { title: "All Systems Red", author: "Martha Wells", cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=300&q=80" },
      { title: "This Is How You Lose the Time War", author: "Amal El-Mohtar", cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "mystery",
    name: "Mystery & Thriller",
    icon: "🔍",
    category: "fiction",
    summary: "Solve gripping whodunits, unmask psychological secrets, and navigate high-stakes suspense.",
    subgenres: ["Cozy Mystery", "Psychological Thriller", "Police Procedural", "Locked-Room Mystery"],
    tropes: ["Unreliable Narrator", "Locked-Room Mystery", "Amateur Sleuth", "Plot Twist"],
    benchmarks: [
      { title: "The Silent Patient", author: "Alex Michaelides", cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=300&q=80" },
      { title: "The Decagon House Murders", author: "Yukito Ayatsuji", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" },
      { title: "The Maid", author: "Nita Prose", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "romance",
    name: "Romance",
    icon: "💖",
    category: "fiction",
    summary: "Heartwarming, emotional, and passionate stories exploring love, relationships, and happy endings.",
    subgenres: ["Contemporary Romance", "Romantasy", "Historical Romance", "Sports Romance"],
    tropes: ["Enemies-to-Lovers", "Fake Dating", "Grumpy x Sunshine", "Second Chance", "Slow Burn"],
    benchmarks: [
      { title: "Book Lovers", author: "Emily Henry", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" },
      { title: "The Love Hypothesis", author: "Ali Hazelwood", cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80" },
      { title: "Fourth Wing", author: "Rebecca Yarros", cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "ya",
    name: "Young Adult (YA)",
    icon: "⚡",
    category: "age-group",
    summary: "Fast-paced coming-of-age journeys filled with high stakes, self-discovery, romance, and adventure.",
    subgenres: ["YA Fantasy", "YA Dystopian", "YA Contemporary", "YA Mystery"],
    tropes: ["Underdog Rebel", "First Love", "Secrets Revealed", "Boarding School"],
    benchmarks: [
      { title: "Legendborn", author: "Tracy Deonn", cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80" },
      { title: "Six of Crows", author: "Leigh Bardugo", cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=300&q=80" },
      { title: "Firekeeper's Daughter", author: "Angeline Boulley", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "middle-grade",
    name: "Middle Grade",
    icon: "🎒",
    category: "age-group",
    summary: "Enchanting adventures tailored for readers ages 8–12, focusing on friendship, courage, and family.",
    subgenres: ["Magical Realism", "Adventure", "Graphic Novels", "Mystery"],
    tropes: ["Hidden Magic", "Group of Friends", "Talking Animals", "Quest"],
    benchmarks: [
      { title: "Skandar & The Unicorn Thief", author: "A.F. Steadman", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" },
      { title: "The Girl Who Drank the Moon", author: "Kelly Barnhill", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" },
      { title: "Amari and the Night Brothers", author: "B.B. Alston", cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "non-fiction",
    name: "Non-Fiction & Memoir",
    icon: "🧠",
    category: "non-fiction",
    summary: "Inspiring real-life accounts, personal memoirs, science, psychology, history, and self-growth.",
    subgenres: ["Memoir", "Self-Improvement", "Popular Science", "History", "Psychology"],
    tropes: ["Real Transformation", "True Story", "Expert Insights"],
    benchmarks: [
      { title: "Braiding Sweetgrass", author: "Robin Wall Kimmerer", cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=300&q=80" },
      { title: "Crying in H Mart", author: "Michelle Zauner", cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80" },
      { title: "Atomic Habits", author: "James Clear", cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "historical-fiction",
    name: "Historical Fiction",
    icon: "⏳",
    category: "fiction",
    summary: "Travel back in time through richly detailed narratives set against real historical eras and events.",
    subgenres: ["WWII Fiction", "Regency", "Ancient Civilizations", "Biographical Fiction"],
    tropes: ["Dual Timelines", "Secret Letters", "Against All Odds"],
    benchmarks: [
      { title: "The Empress of Salt and Fortune", author: "Nghi Vo", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" },
      { title: "Mexican Gothic", author: "Silvia Moreno-Garcia", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" },
      { title: "The Seven Husbands of Evelyn Hugo", author: "Taylor Jenkins Reid", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" }
    ]
  }
];

// MASSIVE 130+ CURATED BOOKS DATABASE
const BOOKS_DATABASE = [
  // --- CHILDREN & MIDDLE GRADE ---
  {
    id: "b-mg-1",
    title: "Amari and the Night Brothers",
    author: "B.B. Alston",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=400&q=80",
    genres: ["middle-grade", "fantasy", "mystery"],
    ageGroup: "middle-grade",
    rating: 4.8,
    reviewsCount: "18,200",
    price: "$9.99",
    pageCount: 416,
    publishedYear: 2021,
    tone: "uplifting",
    tropes: ["Secret Supernatural Agency", "Missing Sibling", "Underdog Magic"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0062975179", barnes: "https://www.barnesandnoble.com/w/amari-and-the-night-brothers-b-b-alston/1136611425", bookshop: "https://bookshop.org/p/books/amari-and-the-night-brothers-b-b-alston/14603348" },
    synopsis: "Amari Peters tries out at the secret Bureau of Supernatural Affairs to find her missing brother.",
    matchReason: "An enchanting, high-energy adventure for Middle Grade readers!"
  },
  {
    id: "b-mg-2",
    title: "Skandar and the Unicorn Thief",
    author: "A.F. Steadman",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.7,
    reviewsCount: "12,400",
    price: "$10.99",
    pageCount: 416,
    publishedYear: 2022,
    tone: "exciting",
    tropes: ["Fierce Ferocious Unicorns", "Elemental Magic Hatching"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1665912739", barnes: "https://www.barnesandnoble.com/w/skandar-and-the-unicorn-thief-a-f-steadman/1139721415", bookshop: "https://bookshop.org/p/books/skandar-and-the-unicorn-thief-a-f-steadman/17512401" },
    synopsis: "Skandar Smith bonds with a ferocious, winged elemental beast to fight a shadowy unicorn thief.",
    matchReason: "A fresh, thrilling twist on middle-grade fantasy featuring wild, fierce elemental unicorns!"
  },
  {
    id: "b-mg-3",
    title: "Percy Jackson: The Lightning Thief",
    author: "Rick Riordan",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.9,
    reviewsCount: "210,000",
    price: "$7.99",
    pageCount: 375,
    publishedYear: 2005,
    tone: "exciting",
    tropes: ["Greek Mythology", "Demigod Hero", "Cross-Country Quest"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0786838655", barnes: "https://www.barnesandnoble.com/w/lightning-thief-rick-riordan/1100052164", bookshop: "https://bookshop.org/p/books/the-lightning-thief-rick-riordan/6703551" },
    synopsis: "12-year-old Percy Jackson discovers he is Poseidon's son and embarks on a quest to save Olympus.",
    matchReason: "Classic, hilarious, and action-packed mythic adventure loved by young readers!"
  },
  {
    id: "b-mg-4",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.9,
    reviewsCount: "350,000",
    price: "$8.99",
    pageCount: 309,
    publishedYear: 1997,
    tone: "exciting",
    tropes: ["Magic Boarding School", "Chosen One", "Trio of Friends"],
    buyLinks: { amazon: "https://www.amazon.com/dp/059035342X", barnes: "https://www.barnesandnoble.com/w/harry-potter-and-the-sorcerers-stone-j-k-rowling/1100035689", bookshop: "https://bookshop.org/p/books/harry-potter-and-the-sorcerer-s-stone-j-k-rowling/6712401" },
    synopsis: "Orphaned Harry Potter discovers on his eleventh birthday that he is a wizard and attends Hogwarts School of Witchcraft and Wizardry.",
    matchReason: "The world-famous magical benchmark classic!"
  },
  {
    id: "b-mg-5",
    title: "Keeper of the Lost Cities",
    author: "Shannon Messenger",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.8,
    reviewsCount: "45,000",
    price: "$9.99",
    pageCount: 496,
    publishedYear: 2012,
    tone: "exciting",
    tropes: ["Telepathic Girl", "Hidden Elvin World", "Foxfire Academy"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1442445939", barnes: "https://www.barnesandnoble.com/w/keeper-of-the-lost-cities-shannon-messenger/1107912415", bookshop: "https://bookshop.org/p/books/keeper-of-the-lost-cities-shannon-messenger/6124100" },
    synopsis: "Sophie Foster is a telepathic girl who discovers she is an elf and attends Foxfire Academy.",
    matchReason: "Beloved middle-grade fantasy series packed with magic and secret origins!"
  },
  {
    id: "b-mg-6",
    title: "Wings of Fire: The Dragonet Prophecy",
    author: "Tui T. Sutherland",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.8,
    reviewsCount: "98,000",
    price: "$7.99",
    pageCount: 336,
    publishedYear: 2012,
    tone: "exciting",
    tropes: ["Prophecy Dragonets", "Dragon Tribes War"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0545349230", barnes: "https://www.barnesandnoble.com/w/the-dragonet-prophecy-tui-t-sutherland/1108912415", bookshop: "https://bookshop.org/p/books/the-dragonet-prophecy-tui-t-sutherland/5124100" },
    synopsis: "Five young dragons raised in secret caves are destined by prophecy to end the war tearing Pyrrhia apart.",
    matchReason: "High-flying dragon fantasy adventure loved by millions of middle-grade readers!"
  },
  {
    id: "b-mg-7",
    title: "Aru Shah and the End of Time",
    author: "Roshani Chokshi",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.7,
    reviewsCount: "22,400",
    price: "$8.99",
    pageCount: 368,
    publishedYear: 2018,
    tone: "exciting",
    tropes: ["Hindu Mythology", "Accidental Sleeper Awakening", "Humorous Heroine"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1368012350", barnes: "https://www.barnesandnoble.com/w/aru-shah-and-the-end-of-time-roshani-chokshi/1126912415", bookshop: "https://bookshop.org/p/books/aru-shah-and-the-end-of-time-roshani-chokshi/11912401" },
    synopsis: "12-year-old Aru Shah accidentally frees the Sleeper while trying to impress her classmates, setting off a quest across Hindu mythology.",
    matchReason: "Hilarious, fast-paced Indian mythology adventure produced by Rick Riordan Presents!"
  },
  {
    id: "b-mg-8",
    title: "The Girl Who Drank the Moon",
    author: "Kelly Barnhill",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.8,
    reviewsCount: "42,000",
    price: "$9.99",
    pageCount: 400,
    publishedYear: 2016,
    tone: "uplifting",
    tropes: ["Moonlight Magic", "Kindly Witch", "Tiny Dragon Companion"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1616205679", barnes: "https://www.barnesandnoble.com/w/the-girl-who-drank-the-moon-kelly-barnhill/1123112415", bookshop: "https://bookshop.org/p/books/the-girl-who-drank-the-moon-kelly-barnhill/9124101" },
    synopsis: "A kindly witch accidentally feeds a baby moonlight instead of starlight, filling her with potent magic.",
    matchReason: "Newbery Medal-winning fairytale fantasy about love, family, and moonlight magic."
  },

  // --- YOUNG ADULT (AGE: ya) ---
  {
    id: "b-ya-1",
    title: "Legendborn",
    author: "Tracy Deonn",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "fantasy"],
    ageGroup: "ya",
    rating: 4.8,
    reviewsCount: "58,000",
    price: "$12.99",
    pageCount: 512,
    publishedYear: 2020,
    tone: "exciting",
    tropes: ["Arthurian Legend Retelling", "Secret College Society", "Root Magic"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1534441609", barnes: "https://www.barnesandnoble.com/w/legendborn-tracy-deonn/1136214512", bookshop: "https://bookshop.org/p/books/legendborn-tracy-deonn/14412056" },
    synopsis: "16-year-old Bree uncovers the Legendborn Order—a secret society of King Arthur's descendants.",
    matchReason: "Incredible contemporary YA urban fantasy blending King Arthur mythos with Southern Black root magic!"
  },
  {
    id: "b-ya-2",
    title: "A Good Girl's Guide to Murder",
    author: "Holly Jackson",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "mystery"],
    ageGroup: "ya",
    rating: 4.6,
    reviewsCount: "98,100",
    price: "$11.20",
    pageCount: 400,
    publishedYear: 2019,
    tone: "dark",
    tropes: ["Amateur Sleuth", "Small-Town Secrets", "True Crime Podcast Vibe"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1984896393", barnes: "https://www.barnesandnoble.com/w/a-good-girls-guide-to-murder-holly-jackson/1131102928", bookshop: "https://bookshop.org/p/books/a-good-girl-s-guide-to-murder-holly-jackson/12762498" },
    synopsis: "Pip Fitz-Amobi chooses a closed 5-year-old local murder case for her senior project to uncover the real killer.",
    matchReason: "Spot-on choice for Young Adult readers craving addictive, twisty murder mysteries!"
  },
  {
    id: "b-ya-3",
    title: "Six of Crows",
    author: "Leigh Bardugo",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "fantasy"],
    ageGroup: "ya",
    rating: 4.9,
    reviewsCount: "165,000",
    price: "$11.99",
    pageCount: 465,
    publishedYear: 2015,
    tone: "exciting",
    tropes: ["Impossible Heist", "Criminal Outcasts", "Found Family Crew"],
    buyLinks: { amazon: "https://www.amazon.com/dp/125007696X", barnes: "https://www.barnesandnoble.com/w/six-of-crows-leigh-bardugo/1121112415", bookshop: "https://bookshop.org/p/books/six-of-crows-leigh-bardugo/8124100" },
    synopsis: "Criminal prodigy Kaz Brekker attempts a deadly heist with six dangerous outcasts.",
    matchReason: "The ultimate YA heist fantasy! Unforgettable characters, sharp banter, and high-stakes action."
  },
  {
    id: "b-ya-4",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "scifi"],
    ageGroup: "ya",
    rating: 4.9,
    reviewsCount: "290,000",
    price: "$9.99",
    pageCount: 374,
    publishedYear: 2008,
    tone: "fast-paced",
    tropes: ["Dystopian Arena", "Archery Heroine", "Rebellion Icon"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0439023521", barnes: "https://www.barnesandnoble.com/w/hunger-games-suzanne-collins/1100171585", bookshop: "https://bookshop.org/p/books/the-hunger-games-suzanne-collins/6712402" },
    synopsis: "16-year-old Katniss Everdeen volunteers to take her sister's place in the Capitol's annual fight-to-the-death Hunger Games.",
    matchReason: "The revolutionary YA dystopian thriller that captivated the globe!"
  },
  {
    id: "b-ya-5",
    title: "The Cruel Prince",
    author: "Holly Black",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80",
    genres: ["ya", "fantasy"],
    ageGroup: "ya",
    rating: 4.7,
    reviewsCount: "115,000",
    price: "$11.99",
    pageCount: 384,
    publishedYear: 2018,
    tone: "dark",
    tropes: ["Mortal in Faerie Court", "Wicked Prince Rivalry", "Political Schemes"],
    buyLinks: { amazon: "https://www.amazon.com/dp/031631031X", barnes: "https://www.barnesandnoble.com/w/the-cruel-prince-holly-black/1126112415", bookshop: "https://bookshop.org/p/books/the-cruel-prince-holly-black/11124101" },
    synopsis: "Jude was seven years old when her parents were murdered and she was stolen away to live in the treacherous High Court of Faerie.",
    matchReason: "Devious, sharp-edged YA faerie political drama with enemies-to-lovers tension."
  },
  {
    id: "b-ya-6",
    title: "One of Us Is Lying",
    author: "Karen M. McManus",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "mystery"],
    ageGroup: "ya",
    rating: 4.6,
    reviewsCount: "105,000",
    price: "$10.99",
    pageCount: 368,
    publishedYear: 2017,
    tone: "dark",
    tropes: ["High School Detention Murder", "Breakfast Club Murder", "Multiple Secrets"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1524714682", barnes: "https://www.barnesandnoble.com/w/one-of-us-is-lying-karen-m-mcmanus/1125112415", bookshop: "https://bookshop.org/p/books/one-of-us-is-lying-karen-m-mcmanus/9124102" },
    synopsis: "Five students walk into detention at Bayview High. Only four walk out alive after school gossip app creator Simon collapses.",
    matchReason: "The Breakfast Club meets Pretty Little Liars in this addictive YA murder mystery!"
  },

  // --- ADULT & NEW ADULT FANTASY / ROMANCE (AGE: adult / new-adult) ---
  {
    id: "b-ad-1",
    title: "Fourth Wing",
    author: "Rebecca Yarros",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["fantasy", "romance"],
    ageGroup: "new-adult",
    rating: 4.7,
    reviewsCount: "142,000",
    price: "$17.49",
    pageCount: 528,
    publishedYear: 2023,
    tone: "exciting",
    tropes: ["Enemies-to-Lovers", "Dragon Riders", "Magic War College"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1649374046", barnes: "https://www.barnesandnoble.com/w/fourth-wing-rebecca-yarros/1142511475", bookshop: "https://bookshop.org/p/books/fourth-wing-rebecca-yarros/19324546" },
    synopsis: "Twenty-year-old Violet Sorrengail enters the deadly Basgiath War College to become a dragon rider.",
    matchReason: "Perfect fit for epic dragon fantasy with electrifying enemies-to-lovers romance and action."
  },
  {
    id: "b-ad-2",
    title: "A Court of Thorns and Roses",
    author: "Sarah J. Maas",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80",
    genres: ["fantasy", "romance"],
    ageGroup: "new-adult",
    rating: 4.8,
    reviewsCount: "250,000",
    price: "$15.99",
    pageCount: 432,
    publishedYear: 2015,
    tone: "exciting",
    tropes: ["Beauty and the Beast Retelling", "Faerie Courts", "Enemies-to-Lovers"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1619634449", barnes: "https://www.barnesandnoble.com/w/a-court-of-thorns-and-roses-sarah-j-maas/1120112415", bookshop: "https://bookshop.org/p/books/a-court-of-thorns-and-roses-sarah-j-maas/8124101" },
    synopsis: "When 19-year-old huntress Feyre kills a wolf in the woods, a terrifying creature demands retribution and drags her to Prythian.",
    matchReason: "The sensational romantasy phenomenon packed with high fae magic and romance!"
  },
  {
    id: "b-ad-3",
    title: "Mistborn: The Final Empire",
    author: "Brandon Sanderson",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    genres: ["fantasy"],
    ageGroup: "adult",
    rating: 4.8,
    reviewsCount: "135,000",
    price: "$14.99",
    pageCount: 541,
    publishedYear: 2006,
    tone: "exciting",
    tropes: ["Allomancy Metal Magic", "Overthrow Dark Lord Heist", "Street Urchin Heroine"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0765350386", barnes: "https://www.barnesandnoble.com/w/mistborn-brandon-sanderson/1100031240", bookshop: "https://bookshop.org/p/books/mistborn-the-final-empire-brandon-sanderson/6712403" },
    synopsis: "In a world where ash falls from the sky and the Lord Ruler reigns supreme, a crew of thieves plans the ultimate heist to overthrow an immortal god.",
    matchReason: "Impeccable metal-ingestion magic system and thrilling heist storyline."
  },

  // --- ADULT SCI-FI (AGE: adult) ---
  {
    id: "b-as-1",
    title: "Dune",
    author: "Frank Herbert",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["scifi"],
    ageGroup: "adult",
    rating: 4.8,
    reviewsCount: "280,000",
    price: "$10.99",
    pageCount: 688,
    publishedYear: 1965,
    tone: "dark",
    tropes: ["Desert Planet Arrakis", "Spice Melange", "Messiah Prophecy"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0441172717", barnes: "https://www.barnesandnoble.com/w/dune-frank-herbert/1100151240", bookshop: "https://bookshop.org/p/books/dune-frank-herbert/6712404" },
    synopsis: "Paul Atreides moves to desert planet Arrakis, sole source of spice melange, where political betrayal forces him into the desert with the Fremen.",
    matchReason: "The monumental sci-fi epic masterpiece of all time!"
  },
  {
    id: "b-as-2",
    title: "Project Hail Mary",
    author: "Andy Weir",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    genres: ["scifi"],
    ageGroup: "adult",
    rating: 4.8,
    reviewsCount: "85,400",
    price: "$15.99",
    pageCount: 496,
    publishedYear: 2021,
    tone: "fast-paced",
    tropes: ["Space Survival", "Unlikely Alliance", "Sci-Fi Problem Solving"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0593135202", barnes: "https://www.barnesandnoble.com/w/project-hail-mary-andy-weir/1137998638", bookshop: "https://bookshop.org/p/books/project-hail-mary-andy-weir/15445214" },
    synopsis: "Ryland Grace is the sole survivor on a desperate mission to save humanity from extinction.",
    matchReason: "Matches your love for fast-paced sci-fi with incredible humor, heart, and smart problem solving!"
  },
  {
    id: "b-as-3",
    title: "Ender's Game",
    author: "Orson Scott Card",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
    genres: ["scifi"],
    ageGroup: "adult",
    rating: 4.8,
    reviewsCount: "190,000",
    price: "$9.99",
    pageCount: 324,
    publishedYear: 1985,
    tone: "fast-paced",
    tropes: ["Battle School Space Station", "Child Genius Commander", "Alien Formics War"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0312853238", barnes: "https://www.barnesandnoble.com/w/enders-game-orson-scott-card/1100161240", bookshop: "https://bookshop.org/p/books/ender-s-game-orson-scott-card/6712405" },
    synopsis: "Young Ender Wiggin is recruited to Battle School in orbit to train as a strategic commander against an alien invasion.",
    matchReason: "Iconic military sci-fi classic filled with tactical brilliance and shocking twists."
  }
];
