/* ==========================================================================
   BOOK NOOK & AI MATCHMAKER - STRICTLY CATEGORIZED BOOK DATABASE
   ========================================================================== */

const GENRES_DATA = [
  {
    id: "fantasy",
    name: "Fantasy",
    icon: "🪄",
    category: "fiction",
    summary: "Immerse yourself in magical worlds, epic quests, mythical creatures, and ancient magic systems.",
    subgenres: ["Epic Fantasy", "Urban Fantasy", "Cozy Fantasy", "Dark Fantasy", "Mythological Fiction"],
    tropes: ["Chosen One", "Enemies-to-Lovers", "Found Family", "Magic School", "Reluctant Hero"],
    benchmarks: [
      { title: "The Way of Kings", author: "Brandon Sanderson", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" },
      { title: "Gideon the Ninth", author: "Tamsyn Muir", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" },
      { title: "Legends & Lattes", author: "Travis Baldree", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "scifi",
    name: "Science Fiction",
    icon: "🚀",
    category: "fiction",
    summary: "Explore futuristic technologies, space travel, dystopian societies, AI revolutions, and alien encounters.",
    subgenres: ["Space Opera", "Cyberpunk", "Dystopian", "Time Travel", "Hard Sci-Fi"],
    tropes: ["AI Awakening", "First Contact", "Dystopian Resistance", "Multiverse Jump"],
    benchmarks: [
      { title: "Project Hail Mary", author: "Andy Weir", cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80" },
      { title: "All Systems Red", author: "Martha Wells", cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=300&q=80" },
      { title: "This Is How You Lose the Time War", author: "Amal El-Mohtar", cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "mystery",
    name: "Mystery & Thriller",
    icon: "🔍",
    category: "fiction",
    summary: "Solve gripping whodunits, unmask psychological secrets, and navigate high-stakes suspense.",
    subgenres: ["Cozy Mystery", "Psychological Thriller", "Police Procedural", "Locked-Room Mystery"],
    tropes: ["Unreliable Narrator", "Locked-Room Mystery", "Amateur Sleuth", "Plot Twist"],
    benchmarks: [
      { title: "The Silent Patient", author: "Alex Michaelides", cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=300&q=80" },
      { title: "The Decagon House Murders", author: "Yukito Ayatsuji", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" },
      { title: "The Maid", author: "Nita Prose", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "romance",
    name: "Romance",
    icon: "💖",
    category: "fiction",
    summary: "Heartwarming, emotional, and passionate stories exploring love, relationships, and happy endings.",
    subgenres: ["Contemporary Romance", "Romantasy", "Historical Romance", "Sports Romance"],
    tropes: ["Enemies-to-Lovers", "Fake Dating", "Grumpy x Sunshine", "Second Chance", "Slow Burn"],
    benchmarks: [
      { title: "Book Lovers", author: "Emily Henry", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" },
      { title: "The Love Hypothesis", author: "Ali Hazelwood", cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80" },
      { title: "Fourth Wing", author: "Rebecca Yarros", cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "ya",
    name: "Young Adult (YA)",
    icon: "⚡",
    category: "age-group",
    summary: "Fast-paced coming-of-age journeys filled with high stakes, self-discovery, romance, and adventure.",
    subgenres: ["YA Fantasy", "YA Dystopian", "YA Contemporary", "YA Mystery"],
    tropes: ["Underdog Rebel", "First Love", "Secrets Revealed", "Boarding School"],
    benchmarks: [
      { title: "Legendborn", author: "Tracy Deonn", cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80" },
      { title: "Six of Crows", author: "Leigh Bardugo", cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=300&q=80" },
      { title: "Firekeeper's Daughter", author: "Angeline Boulley", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "middle-grade",
    name: "Middle Grade",
    icon: "🎒",
    category: "age-group",
    summary: "Enchanting adventures tailored for readers ages 8–12, focusing on friendship, courage, and family.",
    subgenres: ["Magical Realism", "Adventure", "Graphic Novels", "Mystery"],
    tropes: ["Hidden Magic", "Group of Friends", "Talking Animals", "Quest"],
    benchmarks: [
      { title: "Skandar & The Unicorn Thief", author: "A.F. Steadman", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" },
      { title: "The Girl Who Drank the Moon", author: "Kelly Barnhill", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" },
      { title: "Amari and the Night Brothers", author: "B.B. Alston", cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "non-fiction",
    name: "Non-Fiction & Memoir",
    icon: "🧠",
    category: "non-fiction",
    summary: "Inspiring real-life accounts, personal memoirs, science, psychology, history, and self-growth.",
    subgenres: ["Memoir", "Self-Improvement", "Popular Science", "History", "Psychology"],
    tropes: ["Real Transformation", "True Story", "Expert Insights"],
    benchmarks: [
      { title: "Braiding Sweetgrass", author: "Robin Wall Kimmerer", cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=300&q=80" },
      { title: "Crying in H Mart", author: "Michelle Zauner", cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=300&q=80" },
      { title: "Atomic Habits", author: "James Clear", cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=300&q=80" }
    ]
  },
  {
    id: "historical-fiction",
    name: "Historical Fiction",
    icon: "⏳",
    category: "fiction",
    summary: "Travel back in time through richly detailed narratives set against real historical eras and events.",
    subgenres: ["WWII Fiction", "Regency", "Ancient Civilizations", "Biographical Fiction"],
    tropes: ["Dual Timelines", "Secret Letters", "Against All Odds"],
    benchmarks: [
      { title: "The Empress of Salt and Fortune", author: "Nghi Vo", cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80" },
      { title: "Mexican Gothic", author: "Silvia Moreno-Garcia", cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80" },
      { title: "The Seven Husbands of Evelyn Hugo", author: "Taylor Jenkins Reid", cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80" }
    ]
  }
];

// STRICTLY CATEGORIZED BOOK DATABASE
const BOOKS_DATABASE = [
  // --- CHILDREN & MIDDLE-GRADE BOOKS (AGE: middle-grade / children) ---
  {
    id: "b-mg-1",
    title: "Amari and the Night Brothers",
    author: "B.B. Alston",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=400&q=80",
    genres: ["middle-grade", "fantasy", "mystery"],
    ageGroup: "middle-grade",
    rating: 4.8,
    reviewsCount: "18,200",
    price: "$9.99",
    pageCount: 416,
    publishedYear: 2021,
    tone: "uplifting",
    tropes: ["Secret Supernatural Agency", "Missing Sibling", "Underdog Magic"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0062975179", barnes: "https://www.barnesandnoble.com/w/amari-and-the-night-brothers-b-b-alston/1136611425", bookshop: "https://bookshop.org/p/books/amari-and-the-night-brothers-b-b-alston/14603348" },
    synopsis: "Amari Peters tries out at the secret Bureau of Supernatural Affairs to find her missing brother.",
    matchReason: "An enchanting, high-energy adventure for Middle Grade readers who love Percy Jackson!"
  },
  {
    id: "b-mg-2",
    title: "Skandar and the Unicorn Thief",
    author: "A.F. Steadman",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.7,
    reviewsCount: "12,400",
    price: "$10.99",
    pageCount: 416,
    publishedYear: 2022,
    tone: "exciting",
    tropes: ["Fierce Ferocious Unicorns", "Elemental Magic Hatching", "Island Academy"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1665912739", barnes: "https://www.barnesandnoble.com/w/skandar-and-the-unicorn-thief-a-f-steadman/1139721415", bookshop: "https://bookshop.org/p/books/skandar-and-the-unicorn-thief-a-f-steadman/17512401" },
    synopsis: "Skandar Smith bonds with a ferocious, winged elemental beast to fight a shadowy unicorn thief.",
    matchReason: "A fresh, thrilling twist on middle-grade fantasy featuring wild, fierce elemental unicorns!"
  },
  {
    id: "b-mg-3",
    title: "Percy Jackson: The Lightning Thief",
    author: "Rick Riordan",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.9,
    reviewsCount: "210,000",
    price: "$7.99",
    pageCount: 375,
    publishedYear: 2005,
    tone: "exciting",
    tropes: ["Greek Mythology", "Demigod Hero", "Cross-Country Quest"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0786838655", barnes: "https://www.barnesandnoble.com/w/lightning-thief-rick-riordan/1100052164", bookshop: "https://bookshop.org/p/books/the-lightning-thief-rick-riordan/6703551" },
    synopsis: "12-year-old Percy Jackson discovers he is Poseidon's son and embarks on a quest to save Olympus.",
    matchReason: "Classic, hilarious, and action-packed mythic adventure loved by young readers!"
  },
  {
    id: "b-mg-4",
    title: "Tristan Strong Punches a Hole in the Sky",
    author: "Kwame Mbalia",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.8,
    reviewsCount: "15,800",
    price: "$8.99",
    pageCount: 496,
    publishedYear: 2019,
    tone: "exciting",
    tropes: ["African American Folktales", "Anansi & John Henry", "Portal Fantasy Quest"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1368039933", barnes: "https://www.barnesandnoble.com/w/tristan-strong-punches-a-hole-in-the-sky-kwame-mbalia/1131412415", bookshop: "https://bookshop.org/p/books/tristan-strong-punches-a-hole-in-the-sky-kwame-mbalia/12812410" },
    synopsis: "7th grader Tristan punches a hole into Alke, a world of African gods and folktale heroes.",
    matchReason: "High-voltage middle-grade mythology packed with humor, boxing heart, and legends!"
  },
  {
    id: "b-mg-5",
    title: "Keeper of the Lost Cities",
    author: "Shannon Messenger",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.8,
    reviewsCount: "45,000",
    price: "$9.99",
    pageCount: 496,
    publishedYear: 2012,
    tone: "exciting",
    tropes: ["Telepathic Girl", "Hidden Elvin World", "Foxfire Academy"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1442445939", barnes: "https://www.barnesandnoble.com/w/keeper-of-the-lost-cities-shannon-messenger/1107912415", bookshop: "https://bookshop.org/p/books/keeper-of-the-lost-cities-shannon-messenger/6124100" },
    synopsis: "Sophie Foster is a telepathic girl who discovers she is an elf and attends Foxfire Academy.",
    matchReason: "Beloved middle-grade fantasy series packed with magic, friendship, and secret origins!"
  },
  {
    id: "b-mg-6",
    title: "Wings of Fire: The Dragonet Prophecy",
    author: "Tui T. Sutherland",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=300&q=80",
    genres: ["middle-grade", "fantasy"],
    ageGroup: "middle-grade",
    rating: 4.8,
    reviewsCount: "98,000",
    price: "$7.99",
    pageCount: 336,
    publishedYear: 2012,
    tone: "exciting",
    tropes: ["Prophecy Dragonets", "Dragon Tribes War", "Escape Cave"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0545349230", barnes: "https://www.barnesandnoble.com/w/the-dragonet-prophecy-tui-t-sutherland/1108912415", bookshop: "https://bookshop.org/p/books/the-dragonet-prophecy-tui-t-sutherland/5124100" },
    synopsis: "Five young dragons raised in secret caves are destined by prophecy to end the war tearing Pyrrhia apart.",
    matchReason: "High-flying dragon fantasy adventure loved by millions of middle-grade readers worldwide!"
  },

  // --- YOUNG ADULT (AGE: ya) ---
  {
    id: "b-ya-1",
    title: "Legendborn",
    author: "Tracy Deonn",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "fantasy"],
    ageGroup: "ya",
    rating: 4.8,
    reviewsCount: "58,000",
    price: "$12.99",
    pageCount: 512,
    publishedYear: 2020,
    tone: "exciting",
    tropes: ["Arthurian Legend Retelling", "Secret College Society", "Root Magic"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1534441609", barnes: "https://www.barnesandnoble.com/w/legendborn-tracy-deonn/1136214512", bookshop: "https://bookshop.org/p/books/legendborn-tracy-deonn/14412056" },
    synopsis: "16-year-old Bree uncovers the Legendborn Order—a secret society of King Arthur's descendants.",
    matchReason: "Incredible contemporary YA urban fantasy blending King Arthur mythos with Southern Black root magic!"
  },
  {
    id: "b-ya-2",
    title: "A Good Girl's Guide to Murder",
    author: "Holly Jackson",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "mystery"],
    ageGroup: "ya",
    rating: 4.6,
    reviewsCount: "98,100",
    price: "$11.20",
    pageCount: 400,
    publishedYear: 2019,
    tone: "dark",
    tropes: ["Amateur Sleuth", "Small-Town Secrets", "True Crime Podcast Vibe"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1984896393", barnes: "https://www.barnesandnoble.com/w/a-good-girls-guide-to-murder-holly-jackson/1131102928", bookshop: "https://bookshop.org/p/books/a-good-girl-s-guide-to-murder-holly-jackson/12762498" },
    synopsis: "Pip Fitz-Amobi chooses a closed 5-year-old local murder case for her senior project to uncover the real killer.",
    matchReason: "Spot-on choice for Young Adult readers craving addictive, twisty murder mysteries!"
  },
  {
    id: "b-ya-3",
    title: "Six of Crows",
    author: "Leigh Bardugo",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "fantasy"],
    ageGroup: "ya",
    rating: 4.9,
    reviewsCount: "165,000",
    price: "$11.99",
    pageCount: 465,
    publishedYear: 2015,
    tone: "exciting",
    tropes: ["Impossible Heist", "Criminal Outcasts", "Found Family Crew"],
    buyLinks: { amazon: "https://www.amazon.com/dp/125007696X", barnes: "https://www.barnesandnoble.com/w/six-of-crows-leigh-bardugo/1121112415", bookshop: "https://bookshop.org/p/books/six-of-crows-leigh-bardugo/8124100" },
    synopsis: "Criminal prodigy Kaz Brekker attempts a deadly heist with six dangerous outcasts.",
    matchReason: "The ultimate YA heist fantasy! Unforgettable characters, sharp banter, and high-stakes action."
  },
  {
    id: "b-ya-4",
    title: "Divine Rivals",
    author: "Rebecca Ross",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80",
    genres: ["ya", "fantasy", "romance"],
    ageGroup: "ya",
    rating: 4.8,
    reviewsCount: "68,400",
    price: "$12.99",
    pageCount: 368,
    publishedYear: 2023,
    tone: "cozy",
    tropes: ["Rival Journalists", "Enchanted Typewriters", "Secret Letters"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1250857430", barnes: "https://www.barnesandnoble.com/w/divine-rivals-rebecca-ross/1141972415", bookshop: "https://bookshop.org/p/books/divine-rivals-rebecca-ross/18912400" },
    synopsis: "Two young rival journalists form a secret connection through magical typewriters whose letters slip under bedroom doors.",
    matchReason: "Enchanting historical YA fantasy romance filled with secret letters and quiet magic."
  },
  {
    id: "b-ya-5",
    title: "Check & Mate",
    author: "Ali Hazelwood",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "romance"],
    ageGroup: "ya",
    rating: 4.7,
    reviewsCount: "41,000",
    price: "$12.49",
    pageCount: 352,
    publishedYear: 2023,
    tone: "exciting",
    tropes: ["Rival Chess Champions", "Rags to Riches Tournament", "Enemies-to-Lovers"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0593638905", barnes: "https://www.barnesandnoble.com/w/check-mate-ali-hazelwood/1143124150", bookshop: "https://bookshop.org/p/books/check-mate-ali-hazelwood/19812400" },
    synopsis: "Mallory accidentally defeats reigning world chess champion Nolan Sawyer and is drawn back into competitive chess.",
    matchReason: "High-stakes, high-energy YA chess rivalry romance!"
  },
  {
    id: "b-ya-6",
    title: "Daughter of the Moon Goddess",
    author: "Sue Lynn Tan",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=400&q=80",
    genres: ["ya", "fantasy"],
    ageGroup: "ya",
    rating: 4.6,
    reviewsCount: "34,100",
    price: "$13.99",
    pageCount: 512,
    publishedYear: 2022,
    tone: "uplifting",
    tropes: ["Chinese Mythology", "Moon Goddess", "Celestial Archery Quest"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0063031329", barnes: "https://www.barnesandnoble.com/w/daughter-of-the-moon-goddess-sue-lynn-tan/1139412415", bookshop: "https://bookshop.org/p/books/daughter-of-the-moon-goddess-sue-lynn-tan/17154211" },
    synopsis: "Xingyin flees the moon and embarks on a quest to save her hidden mother from the Celestial Emperor.",
    matchReason: "Lyrical Chinese mythic fantasy featuring archery, celestial kingdoms, and fierce devotion."
  },

  // --- NEW ADULT & ADULT FANTASY / ROMANCE (AGE: new-adult / adult) ---
  {
    id: "b-ad-1",
    title: "Fourth Wing",
    author: "Rebecca Yarros",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["fantasy", "romance"],
    ageGroup: "new-adult",
    rating: 4.7,
    reviewsCount: "142,000",
    price: "$17.49",
    pageCount: 528,
    publishedYear: 2023,
    tone: "exciting",
    tropes: ["Enemies-to-Lovers", "Dragon Riders", "Magic War College"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1649374046", barnes: "https://www.barnesandnoble.com/w/fourth-wing-rebecca-yarros/1142511475", bookshop: "https://bookshop.org/p/books/fourth-wing-rebecca-yarros/19324546" },
    synopsis: "Twenty-year-old Violet Sorrengail enters the deadly Basgiath War College to become a dragon rider.",
    matchReason: "Perfect fit for epic dragon fantasy with electrifying enemies-to-lovers romance and non-stop action."
  },
  {
    id: "b-ad-2",
    title: "Legends & Lattes",
    author: "Travis Baldree",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=400&q=80",
    genres: ["fantasy"],
    ageGroup: "adult",
    rating: 4.6,
    reviewsCount: "45,000",
    price: "$13.99",
    pageCount: 304,
    publishedYear: 2022,
    tone: "cozy",
    tropes: ["Cozy Fantasy", "Retired Adventurer", "Coffee Shop Owner"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1250886088", barnes: "https://www.barnesandnoble.com/w/legends-lattes-travis-baldree/1141369324", bookshop: "https://bookshop.org/p/books/legends-lattes-travis-baldree/18485290" },
    synopsis: "Viv, a female orc barbarian, hangs up her sword to open the first-ever coffee shop in Thune.",
    matchReason: "The ultimate cozy fantasy read! Heartwarming, comforting, and low-stakes comfort reading."
  },
  {
    id: "b-ad-3",
    title: "Gideon the Ninth",
    author: "Tamsyn Muir",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=400&q=80",
    genres: ["fantasy", "scifi"],
    ageGroup: "adult",
    rating: 4.6,
    reviewsCount: "48,300",
    price: "$13.99",
    pageCount: 448,
    publishedYear: 2019,
    tone: "dark",
    tropes: ["Lesbian Necromancers in Space", "Gothic Mansion", "Snarky Heroine"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1250313198", barnes: "https://www.barnesandnoble.com/w/gideon-the-ninth-tamsyn-muir/1129994389", bookshop: "https://bookshop.org/p/books/gideon-the-ninth-tamsyn-muir/12061035" },
    synopsis: "Gideon has a sword and no time for undead bullshit. Brought along to a gothic palace, she fights for survival.",
    matchReason: "Cult-classic dark fantasy with witty snark, gothic horror, and sword-fighting necromancers!"
  },
  {
    id: "b-ad-4",
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=400&q=80",
    genres: ["fantasy"],
    ageGroup: "adult",
    rating: 4.8,
    reviewsCount: "95,200",
    price: "$13.59",
    pageCount: 396,
    publishedYear: 2020,
    tone: "cozy",
    tropes: ["Found Family", "Magical Orphanage", "Wholesome Warmth"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1250217288", barnes: "https://www.barnesandnoble.com/w/the-house-in-the-cerulean-sea-tj-klune/1131713295", bookshop: "https://bookshop.org/p/books/the-house-in-the-cerulean-sea-tj-klune/12762499" },
    synopsis: "By-the-book caseworker Linus Baker evaluates a secretive island orphanage housing six magical children.",
    matchReason: "A heartwarming, soul-soothing cozy fantasy like a warm cup of hot chocolate on a rainy day."
  },
  {
    id: "b-ad-5",
    title: "Emily Wilde's Encyclopaedia of Faeries",
    author: "Heather Fawcett",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80",
    genres: ["fantasy"],
    ageGroup: "adult",
    rating: 4.6,
    reviewsCount: "42,100",
    price: "$14.99",
    pageCount: 336,
    publishedYear: 2023,
    tone: "cozy",
    tropes: ["Grumpy Scholar", "Cozy Faerie Folklore", "Academic Rivals"],
    buyLinks: { amazon: "https://www.amazon.com/dp/059350013X", barnes: "https://www.barnesandnoble.com/w/emily-wildes-encyclopaedia-of-faeries-heather-fawcett/1141361240", bookshop: "https://bookshop.org/p/books/emily-wilde-s-encyclopaedia-of-faeries-heather-fawcett/18485295" },
    synopsis: "Professor Emily Wilde travels to a snowy Nordic village to study faeries alongside her academic rival.",
    matchReason: "Delightful cozy fantasy for fans of folklore, snowy atmospheres, and scholarly grumpiness."
  },

  // --- ADULT SCI-FI (AGE: adult) ---
  {
    id: "b-as-1",
    title: "Project Hail Mary",
    author: "Andy Weir",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80",
    genres: ["scifi"],
    ageGroup: "adult",
    rating: 4.8,
    reviewsCount: "85,400",
    price: "$15.99",
    pageCount: 496,
    publishedYear: 2021,
    tone: "fast-paced",
    tropes: ["Space Survival", "Unlikely Alliance", "Sci-Fi Problem Solving"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0593135202", barnes: "https://www.barnesandnoble.com/w/project-hail-mary-andy-weir/1137998638", bookshop: "https://bookshop.org/p/books/project-hail-mary-andy-weir/15445214" },
    synopsis: "Ryland Grace is the sole survivor on a desperate mission to save humanity from extinction.",
    matchReason: "Matches your love for fast-paced sci-fi with incredible humor, heart, and smart problem solving!"
  },
  {
    id: "b-as-2",
    title: "All Systems Red (The Murderbot Diaries)",
    author: "Martha Wells",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["scifi"],
    ageGroup: "adult",
    rating: 4.7,
    reviewsCount: "62,100",
    price: "$11.99",
    pageCount: 160,
    publishedYear: 2017,
    tone: "cozy",
    tropes: ["Reluctant AI Hero", "Social Anxiety Security Android"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0765397526", barnes: "https://www.barnesandnoble.com/w/all-systems-red-martha-wells/1125206497", bookshop: "https://bookshop.org/p/books/all-systems-red-martha-wells/8672051" },
    synopsis: "A security android hacks its governor module and calls itself 'Murderbot' to watch soap operas.",
    matchReason: "A beloved niche sci-fi novella! Hilarious, fast-paced, and centered around a security unit."
  },
  {
    id: "b-as-3",
    title: "Dark Matter",
    author: "Blake Crouch",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
    genres: ["scifi", "mystery"],
    ageGroup: "adult",
    rating: 4.7,
    reviewsCount: "92,000",
    price: "$13.99",
    pageCount: 352,
    publishedYear: 2016,
    tone: "fast-paced",
    tropes: ["Multiverse Box", "Alternate Lives", "Mind-Bending Thriller"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1101904240", barnes: "https://www.barnesandnoble.com/w/dark-matter-blake-crouch/1122612415", bookshop: "https://bookshop.org/p/books/dark-matter-blake-crouch/9812400" },
    synopsis: "Jason Dessen wakes up in an alternate life where he invented multiverse travel instead of getting married.",
    matchReason: "An addictive, non-stop sci-fi thriller exploring the paths we didn't take!"
  },

  // --- ADULT MYSTERY & THRILLER (AGE: adult) ---
  {
    id: "b-am-1",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=400&q=80",
    genres: ["mystery"],
    ageGroup: "adult",
    rating: 4.6,
    reviewsCount: "185,000",
    price: "$13.99",
    pageCount: 336,
    publishedYear: 2019,
    tone: "dark",
    tropes: ["Mute Murderess", "Obsessive Psychotherapist", "Unreliable Narrator"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1250301696", barnes: "https://www.barnesandnoble.com/w/the-silent-patient-alex-michaelides/1128912415", bookshop: "https://bookshop.org/p/books/the-silent-patient-alex-michaelides/12124101" },
    synopsis: "Alicia Berenson shoots her husband five times in the face and never speaks another word.",
    matchReason: "A massive psychological thriller bestseller with one of the most famous twists in modern mystery!"
  },
  {
    id: "b-am-2",
    title: "The Decagon House Murders",
    author: "Yukito Ayatsuji",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=400&q=80",
    genres: ["mystery"],
    ageGroup: "adult",
    rating: 4.5,
    reviewsCount: "14,200",
    price: "$14.95",
    pageCount: 288,
    publishedYear: 1987,
    tone: "dark",
    tropes: ["Japanese Honkaku Mystery", "Isolated Island", "Locked-Room Murder"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1913193630", barnes: "https://www.barnesandnoble.com/w/the-decagon-house-murders-yukito-ayatsuji/1138402134", bookshop: "https://bookshop.org/p/books/the-decagon-house-murders-yukito-ayatsuji/15672100" },
    synopsis: "Seven mystery club members stay in a ten-sided house on an isolated island where murder strikes.",
    matchReason: "A masterclass niche locked-room murder mystery from the father of Japanese Honkaku detective fiction!"
  },
  {
    id: "b-am-3",
    title: "The Maid",
    author: "Nita Prose",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
    genres: ["mystery"],
    ageGroup: "adult",
    rating: 4.5,
    reviewsCount: "74,000",
    price: "$12.49",
    pageCount: 304,
    publishedYear: 2022,
    tone: "cozy",
    tropes: ["Neurodivergent Sleuth", "Hotel Murder", "Cozy Whodunit"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0593356152", barnes: "https://www.barnesandnoble.com/w/the-maid-nita-prose/1139412513", bookshop: "https://bookshop.org/p/books/the-maid-nita-prose/17154210" },
    synopsis: "Hotel maid Molly Gray discovers a dead billionaire in his suite and becomes the chief suspect.",
    matchReason: "A charming, heartwarming cozy mystery centered on an unforgettable, unique sleuth."
  },

  // --- ADULT NON-FICTION & MEMOIR (AGE: adult) ---
  {
    id: "b-anf-1",
    title: "Atomic Habits",
    author: "James Clear",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=400&q=80",
    genres: ["non-fiction"],
    ageGroup: "adult",
    rating: 4.8,
    reviewsCount: "135,000",
    price: "$14.79",
    pageCount: 320,
    publishedYear: 2018,
    tone: "uplifting",
    tropes: ["Self Improvement", "Habit Building"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0735211299", barnes: "https://www.barnesandnoble.com/w/atomic-habits-james-clear/1129188094", bookshop: "https://bookshop.org/p/books/atomic-habits-james-clear/12185790" },
    synopsis: "Atomic Habits offers a framework for improving every day through tiny behavioral gains.",
    matchReason: "Invaluable non-fiction recommendation for anyone seeking actionable self-growth."
  },
  {
    id: "b-anf-2",
    title: "Braiding Sweetgrass",
    author: "Robin Wall Kimmerer",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80",
    genres: ["non-fiction"],
    ageGroup: "adult",
    rating: 4.9,
    reviewsCount: "42,000",
    price: "$15.25",
    pageCount: 390,
    publishedYear: 2013,
    tone: "uplifting",
    tropes: ["Indigenous Wisdom", "Botanical Science"],
    buyLinks: { amazon: "https://www.amazon.com/dp/1571313567", barnes: "https://www.barnesandnoble.com/w/braiding-sweetgrass-robin-wall-kimmerer/1114981245", bookshop: "https://bookshop.org/p/books/braiding-sweetgrass-robin-wall-kimmerer/7241240" },
    synopsis: "A Potawatomi botanist bridges scientific analysis with indigenous wisdom.",
    matchReason: "A profound, poetic non-fiction masterpiece bridging indigenous knowledge with science."
  },
  {
    id: "b-anf-3",
    title: "Crying in H Mart",
    author: "Michelle Zauner",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=400&q=80",
    genres: ["non-fiction"],
    ageGroup: "adult",
    rating: 4.7,
    reviewsCount: "71,000",
    price: "$14.00",
    pageCount: 256,
    publishedYear: 2021,
    tone: "emotional",
    tropes: ["Mother-Daughter Relationship", "Korean Food & Identity"],
    buyLinks: { amazon: "https://www.amazon.com/dp/0525657746", barnes: "https://www.barnesandnoble.com/w/crying-in-h-mart-michelle-zauner/1137451240", bookshop: "https://bookshop.org/p/books/crying-in-h-mart-michelle-zauner/15241250" },
    synopsis: "Michelle Zauner shares a powerful memoir of growing up Korean American, food, and loss.",
    matchReason: "A deeply moving memoir about food, grief, motherly love, and cultural identity."
  }
];
